# Generated by Django 5.1 on 2024-08-24 18:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-data_criacao'], 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='perguntas',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='pontuacao',
        ),
        migrations.AddField(
            model_name='quiz',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Determina se o quiz está ativo ou não'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Data de criação do quiz'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição opcional do quiz'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='nome',
            field=models.CharField(help_text='Nome do quiz', max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='posicao',
            field=models.CharField(help_text='Posição ou categoria do quiz', max_length=100),
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(help_text='Texto da pergunta')),
                ('pontuacao', models.IntegerField(default=0, help_text='Pontuação atribuída à pergunta')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='app.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(help_text='Texto da resposta', max_length=255)),
                ('correta', models.BooleanField(default=False, help_text='Marca se a resposta está correta')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='app.pergunta')),
            ],
        ),
    ]
