# Generated by Django 5.1 on 2024-08-26 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_quiz_options_remove_quiz_perguntas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pergunta',
            name='quiz',
        ),
        migrations.AlterModelOptions(
            name='pergunta',
            options={'verbose_name_plural': 'Perguntas'},
        ),
        migrations.AlterModelOptions(
            name='resposta',
            options={'verbose_name_plural': 'Respostas'},
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='pontuacao',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='texto',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Configuracao',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
